import type { Project, Consultation, PreferenceProfile, DesignLibraryItem, GeneratedConcept, ReferenceItem } from "@/types";

// Unsplash interior design image IDs for demo
export const DEMO_IMAGES = {
  styles: {
    modern: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=800&q=80",
    minimal: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
    contemporary: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&q=80",
    luxury: "https://images.unsplash.com/photo-1615873968403-89e068629265?w=800&q=80",
    scandinavian: "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=800&q=80",
    japandi: "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800&q=80",
    industrial: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
    traditional: "https://images.unsplash.com/photo-1616627561950-9f746e330187?w=800&q=80",
    neoclassical: "https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800&q=80",
    warm_wooden: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80",
    modern_classic: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
    organic: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?w=800&q=80",
  },
  rooms: {
    living_room_1: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
    living_room_2: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=800&q=80",
    living_room_3: "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&q=80",
    bedroom_1: "https://images.unsplash.com/photo-1615873968403-89e068629265?w=800&q=80",
    bedroom_2: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80",
    bedroom_3: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&q=80",
    kitchen_1: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
    kitchen_2: "https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=800&q=80",
    dining_1: "https://images.unsplash.com/photo-1615529182904-14819c35db37?w=800&q=80",
    foyer_1: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
  },
  concepts: {
    concept_1: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&q=80",
    concept_2: "https://images.unsplash.com/photo-1615873968403-89e068629265?w=1200&q=80",
    concept_3: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=1200&q=80",
  },
};

export const DEMO_PROJECTS: Project[] = [
  {
    id: "demo-project-1",
    designerId: "demo-designer",
    clientId: "demo-client-1",
    clientName: "Rahul Sharma",
    name: "4 BHK Residential Apartment",
    propertyType: "apartment",
    bhk: 4,
    location: "Banjara Hills, Hyderabad",
    status: "concept_generation",
    thumbnailUrl: DEMO_IMAGES.rooms.bedroom_1,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: "demo-project-2",
    designerId: "demo-designer",
    clientId: "demo-client-2",
    clientName: "Priya & Arjun Mehta",
    name: "Villa Interior — Phase 1",
    propertyType: "villa",
    location: "Jubilee Hills, Hyderabad",
    status: "reference_selection",
    thumbnailUrl: DEMO_IMAGES.rooms.living_room_1,
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: "demo-project-3",
    designerId: "demo-designer",
    clientId: "demo-client-3",
    clientName: "Kavitha Reddy",
    name: "Corporate Office — 3rd Floor",
    propertyType: "office",
    location: "HITEC City, Hyderabad",
    status: "summary",
    thumbnailUrl: DEMO_IMAGES.rooms.living_room_3,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
];

export const DEMO_PREFERENCE_PROFILE: PreferenceProfile = {
  id: "demo-profile-1",
  consultationId: "demo-consultation-1",
  projectId: "demo-project-1",
  overallStyle: ["minimal", "luxury"],
  palette: ["beige", "warm_neutrals", "wood_heavy"],
  materials: ["Walnut", "Matte Laminate", "Fabric", "Natural Stone"],
  lighting: ["warm_ambient", "indirect"],
  furniture: ["minimal", "soft_curves"],
  ornamentation: "minimal",
  confidence: { overallStyle: 0.91, palette: 0.84, lighting: 0.78, materials: 0.72 },
  likedReferenceIds: [],
  dislikedReferenceIds: [],
  avoid: ["Heavy ornamentation", "Dark tones", "Industrial elements"],
  version: 3,
  updatedAt: new Date(),
};

export const DEMO_LIBRARY_ITEMS: DesignLibraryItem[] = [
  {
    id: "lib-1", designerId: "demo-designer",
    storagePath: "library/lib-1.jpg", publicUrl: DEMO_IMAGES.rooms.bedroom_1,
    room: "master_bedroom", element: "Dressing Area", style: ["minimal", "luxury"],
    palette: ["beige", "warm_neutrals"], materials: ["Walnut", "Matte Laminate"],
    lighting: "warm_ambient", tags: ["wardrobe", "dressing", "walnut", "minimal"],
    description: "Minimal walnut dressing area with integrated vanity", createdAt: new Date(),
  },
  {
    id: "lib-2", designerId: "demo-designer",
    storagePath: "library/lib-2.jpg", publicUrl: DEMO_IMAGES.rooms.bedroom_2,
    room: "master_bedroom", element: "Headboard Wall", style: ["luxury", "contemporary"],
    palette: ["warm_neutrals", "beige"], materials: ["Fabric", "Walnut"],
    lighting: "warm_ambient", tags: ["headboard", "fabric", "luxury"],
    description: "Upholstered headboard with warm lighting", createdAt: new Date(),
  },
  {
    id: "lib-3", designerId: "demo-designer",
    storagePath: "library/lib-3.jpg", publicUrl: DEMO_IMAGES.rooms.living_room_1,
    room: "living_room", element: "Sofa", style: ["minimal", "contemporary"],
    palette: ["cool_neutrals", "warm_neutrals"], materials: ["Fabric"],
    lighting: "indirect", tags: ["sofa", "minimal", "contemporary"],
    description: "Low-profile sectional sofa", createdAt: new Date(),
  },
  {
    id: "lib-4", designerId: "demo-designer",
    storagePath: "library/lib-4.jpg", publicUrl: DEMO_IMAGES.rooms.living_room_2,
    room: "living_room", element: "Feature Wall", style: ["modern", "minimal"],
    palette: ["warm_neutrals"], materials: ["Fluted Panels", "Walnut"],
    lighting: "indirect", tags: ["feature wall", "fluted", "tv unit"],
    description: "Fluted panel feature wall with integrated TV unit", createdAt: new Date(),
  },
  {
    id: "lib-5", designerId: "demo-designer",
    storagePath: "library/lib-5.jpg", publicUrl: DEMO_IMAGES.rooms.kitchen_1,
    room: "kitchen", element: "Base Cabinets", style: ["minimal", "modern"],
    palette: ["pure_white", "warm_neutrals"], materials: ["Matte Laminate", "Natural Stone"],
    lighting: "bright", tags: ["kitchen", "island", "minimal", "white"],
    description: "Matte white modular kitchen with stone countertop", createdAt: new Date(),
  },
  {
    id: "lib-6", designerId: "demo-designer",
    storagePath: "library/lib-6.jpg", publicUrl: DEMO_IMAGES.rooms.bedroom_3,
    room: "master_bedroom", element: "Wardrobe", style: ["luxury", "minimal"],
    palette: ["warm_neutrals", "wood_heavy"], materials: ["Walnut", "Glass"],
    lighting: "warm_ambient", tags: ["wardrobe", "full-height", "walnut"],
    description: "Full-height walnut wardrobe with glass inserts", createdAt: new Date(),
  },
  {
    id: "lib-7", designerId: "demo-designer",
    storagePath: "library/lib-7.jpg", publicUrl: DEMO_IMAGES.rooms.dining_1,
    room: "dining_room", element: "Dining Table", style: ["modern", "luxury"],
    palette: ["earth_tones", "warm_neutrals"], materials: ["Natural Wood", "Metal"],
    lighting: "decorative", tags: ["dining", "marble", "pendant"],
    description: "Marble-top dining table with pendant lighting", createdAt: new Date(),
  },
  {
    id: "lib-8", designerId: "demo-designer",
    storagePath: "library/lib-8.jpg", publicUrl: DEMO_IMAGES.rooms.foyer_1,
    room: "foyer", element: "Console", style: ["neoclassical", "luxury"],
    palette: ["warm_neutrals", "earth_tones"], materials: ["Marble", "Metal"],
    lighting: "decorative", tags: ["foyer", "console", "marble", "luxury"],
    description: "Marble console with brass accents and statement mirror", createdAt: new Date(),
  },
];

export const DEMO_CONCEPTS: GeneratedConcept[] = [
  {
    id: "concept-demo-1",
    consultationId: "demo-consultation-1",
    projectId: "demo-project-1",
    room: "master_bedroom",
    element: "Dressing Area",
    imageUrl: DEMO_IMAGES.concepts.concept_1,
    prompt: "Minimal luxury master bedroom dressing area with walnut wardrobe, warm ambient lighting, beige palette",
    referencesUsed: ["lib-1", "lib-6"],
    provider: "demo",
    model: "demo-v1",
    promptVersion: "v1.0",
    savedToProject: true,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: "concept-demo-2",
    consultationId: "demo-consultation-1",
    projectId: "demo-project-1",
    room: "master_bedroom",
    element: "Dressing Area",
    imageUrl: DEMO_IMAGES.concepts.concept_2,
    prompt: "Full-height wardrobe with glass panels, walnut finish, integrated lighting strips",
    referencesUsed: ["lib-1", "lib-6"],
    parentConceptId: "concept-demo-1",
    refinementInstruction: "Make the wardrobe full height with glass inserts",
    provider: "demo",
    model: "demo-v1",
    promptVersion: "v1.0",
    savedToProject: false,
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
  },
];

export const DEMO_REFERENCES: ReferenceItem[] = [
  { id: "ref-ext-1", imageUrl: DEMO_IMAGES.styles.modern, source: "external", title: "Modern Living Room", style: ["modern"], relevanceScore: 0.92 },
  { id: "ref-ext-2", imageUrl: DEMO_IMAGES.styles.minimal, source: "external", title: "Minimal Interior", style: ["minimal"], relevanceScore: 0.89 },
  { id: "ref-ext-3", imageUrl: DEMO_IMAGES.styles.japandi, source: "external", title: "Japandi Bedroom", style: ["japandi"], relevanceScore: 0.85 },
  { id: "ref-ext-4", imageUrl: DEMO_IMAGES.styles.scandinavian, source: "external", title: "Scandinavian Warmth", style: ["scandinavian"], relevanceScore: 0.81 },
  { id: "ref-ext-5", imageUrl: DEMO_IMAGES.styles.luxury, source: "external", title: "Luxury Dressing", style: ["luxury"], relevanceScore: 0.88 },
  { id: "ref-ext-6", imageUrl: DEMO_IMAGES.styles.warm_wooden, source: "external", title: "Warm Wood Interior", style: ["warm_wooden"], relevanceScore: 0.76 },
];

export const DEMO_STYLE_IMAGES: Record<string, string> = DEMO_IMAGES.styles;
